### ISSUE TITLE
Hyperswarm implementation

### ISSUE THREAD

**Issue by Metallistener** [holepunchto/react-native-bare-kit#4]
Hi! Can I connect Hyperswarm with this library to make DHT connection? If yes then I don't understand how we can use Worklet and Hyperswarm together.

**Comment by kasperisager** [comment]
Yes, Bare can already run Hyperswarm so you just import it from your worklet code and use it.

**Comment by Metallistener** [comment]
> Yes, Bare can already run Hyperswarm so you just import it from your worklet code and use it.

Can you give any example how to import hyperswarm using worklet? Sorry, we just don't understand to do it

**Comment by kasperisager** [comment]
Here's one way:

`worklet.js`
```
const Hyperswarm = require('hyperswarm')
```
```
$ bare-dev bundle -o worklet.bundle.js worklet.js
```

`app.js`
```
worklet.start('/worklet.bundle', require('./worklet.bundle'))
```

**Comment by Metallistener** [comment]
> Here's one way:
> 
> `worklet.js`
> 
> ```
> const Hyperswarm = require('hyperswarm')
> ```
> 
> ```
> $ bare-dev bundle -o worklet.bundle.js worklet.js
> ```
> 
> `app.js`
> 
> ```
> worklet.start('/worklet.bundle', require('./worklet.bundle'))
> ```

Now we got it! Thx ser!

**Comment by Metallistener** [comment]
> bare-dev bundle -o worklet.bundle.js worklet.js

GM ser! Is there any documentation where we can find instruction how to communicate client side with worklet.js file where hyperswarm etc are placed?

**Comment by kasperisager** [comment]
There's an RPC example in https://github.com/holepunchto/react-native-bare-kit?tab=readme-ov-file#usage.

**Comment by n9lsjr** [comment]
> Here's one way:
> 
> `worklet.js`
> 
> ```
> const Hyperswarm = require('hyperswarm')
> ```
> 
> ```
> $ bare-dev bundle -o worklet.bundle.js worklet.js
> ```
> 
> `app.js`
> 
> ```
> worklet.start('/worklet.bundle', require('./worklet.bundle'))
> ```

How would one go about if you want to bundle many files? Do you start a worklet for every file in the "bare" section once the React hermes engine is started??
