### ISSUE TITLE
AssembleRelease (android) error

### ISSUE THREAD

**Issue by Metallistener** [holepunchto/react-native-bare-kit#5]
GM! When we try to build dev android APK file using ./gradlew assembleRelease script we get the next error about local .aar file in react-native-bare-kit library

<img width="1235" alt="Снимок экрана 2024-10-22 в 14 00 57" src="https://github.com/user-attachments/assets/2065dfa6-fdc8-4775-b2ac-71bdd53e8262">

Is there any solutions how to resolve this problem?

**Comment by kasperisager** [comment]
This should have been already solved by b9280659b7bb4a34ac671a7ecf0e89e50c49a797. Could you try updating?

**Comment by Metallistener** [comment]
> This should have been already solved by [b928065](https://github.com/holepunchto/react-native-bare-kit/commit/b9280659b7bb4a34ac671a7ecf0e89e50c49a797). Could you try updating?

Worked well!
