### ISSUE TITLE
Crash of APK file

### ISSUE THREAD

**Issue by Metallistener** [holepunchto/react-native-bare-kit#6]
After building APK using ./gradlew assembleRelease script and installing APK on device I catch crash of application
After checking logs I've found this error
<img width="631" alt="Снимок экрана 2024-10-24 в 13 57 48" src="https://github.com/user-attachments/assets/fd15332c-58c2-4493-9f9e-2ff09971868b">

**Uncaught AddonError: ADDON_NOT_FOUND: Cannot find addon '/worklet.bundle/node_modules/udx-native' imported from 'file:///worklet.bundle/node_modules/node-gyp-build/index.js'**

P.S. It happens only with APK file. If you run app locally using npm run android then everything works well

**Comment by kasperisager** [comment]
Could you unpack the APK and check if it actually includes `libudx-native.<version>.so`?

**Comment by Metallistener** [comment]
> libudx-native

Yes the APK includes libudx-native.<version>.so

![Uploading Снимок экрана 2024-10-28 в 09.44.27.png…]()

**Comment by kasperisager** [comment]
You're sure the file is named `libudx-native.1.13.3.50`?

**Comment by Metallistener** [comment]
> You're sure the file is named `libudx-native.1.13.3.50`?

There is error because of copying **50 === so**

**Comment by Metallistener** [comment]
<img width="723" alt="Снимок экрана 2024-10-28 в 12 07 56" src="https://github.com/user-attachments/assets/72029fab-faa4-4a65-8ac5-2e7b685b8f5a">

**Comment by Metallistener** [comment]
@kasperisager GM ser! Is there any update about the problem? Maybe I can provide you something else to debug the problem?

P.S. If I remove this part of code **worklet.start('/worklet.bundle', require('./worklet.bundle'))** then there is no crash

**Comment by kasperisager** [comment]
Morning! I haven't had time to dig into this more on my end, no. Could you try doing `dlopen('libudx-native.1.13.3.so')` to check if that fails?

**Comment by Metallistener** [comment]
> Morning! I haven't had time to dig into this more on my end, no. Could you try doing `dlopen('libudx-native.1.13.3.so')` to check if that fails?

I've found the reason of crash. I've just built worklet bundle again and now it works fine
